# -*- coding: utf-8 -*-
"""Atribuição.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WYBXlRHikaMEhGxFV413weO88-EmWd2F
"""

x=8
print(x)
x+=5
print(x)
x-=4
print(x)
x*=20
print(x)
x/=2
print(x)