# -*- coding: utf-8 -*-
"""Comparação.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xPhCPxJp9e0hr7pWZned78Hb8zfFPHJI
"""

x=8
print(x)
x1=3
print(x)
X_Result=x<x1
print(X_Result)
X_Result=x==x1
print(X_Result)
X_Result=x>=x1
print(X_Result)
X_Result=x!=x1
print(X_Result)