# -*- coding: utf-8 -*-
"""Operadores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dd-bXJlmHnmpBtKbVZylQs1EKdRjFvau
"""

x=6+4*2
print(x)
x=(4*9+5)
print(x)
x=((6+7)*9)
print(x)
x=(15+20-30)
print(x)
x=(6+5**2)
print(x)